# Generated by Django 3.1.4 on 2022-11-23 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSync',
            fields=[
                ('serial_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('status_in_css', models.IntegerField()),
                ('status_in_cbcm', models.IntegerField()),
                ('job_status', models.IntegerField(default=0)),
                ('mismatch_identified_on', models.DateTimeField(default=datetime.datetime(2022, 11, 23, 12, 22, 32, 95669))),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FixedNumberSync',
            fields=[
                ('fixed_number', models.IntegerField(primary_key=True, serialize=False)),
                ('status_in_css', models.IntegerField()),
                ('status_in_cbcm', models.IntegerField()),
                ('job_status', models.IntegerField(default=0)),
                ('mismatch_identified_on', models.DateTimeField(default=datetime.datetime(2022, 11, 23, 12, 22, 32, 95669))),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20)),
                ('job_status', models.IntegerField(default=0)),
                ('src_system', models.CharField(max_length=20)),
                ('target_system', models.CharField(max_length=20)),
                ('pending_records', models.BooleanField(default=False)),
                ('run_date', models.DateTimeField(default=datetime.datetime(2022, 11, 23, 12, 22, 32, 95669))),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NumberSync',
            fields=[
                ('msisdn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status_in_css', models.IntegerField()),
                ('status_in_cbcm', models.IntegerField()),
                ('job_status', models.IntegerField(default=0)),
                ('mismatch_identified_on', models.DateTimeField(default=datetime.datetime(2022, 11, 23, 12, 22, 32, 95669))),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
